version: '3'
services: 
  takehome-pg:
    image: "postgres:10"
    environment: 
     - POSTGRES_DB=mpharma
  web:
    build: .
    image: app
    command: > 
      sh -c "sleep 10 && 
             npm run migrate && 
             npm start"
    environment:
     - NODE_ENV=development
     - PGHOST=takehome-pg
    ports:
     - "5000:5000"
    depends_on:
    - takehome-pg