#! /bin/bash

if [ "$1" == 'down' ]; then
    read -p "Are you sure you want to drop the database? Y/N " reply
    if [ "$reply" == 'Y' -o "$reply" == 'y' ]; then
        psql -h localhost -U postgres -c "DROP DATABASE mpharma"
    fi
else
    #create the database if it does not exist
    psql -h localhost -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'mpharma'" | grep -q 1 || psql -h localhost -U postgres -c "CREATE DATABASE mpharma"
  
    #run the migration scripts
    current_dir=`dirname $0`
    for file in "$current_dir/initial/*.sql"
    do
        psql -h localhost -U postgres -f $file -d mpharma
    done;
fi
